app:
    resource: "@AppBundle/Controller/"
    type:     annotation
login:
    pattern:   /login
    defaults:  { _controller: AppBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
oneup_uploader:
    resource: .
    type: uploader
